### PR TITLE
Do not call memcpy with nullptr

### PR DESCRIPTION
**Pull request by e00E**
This is undefined behavior even if count is 0.

### CODE REVIEW

**Comment by rswinkle** [comment]
It's funny you made this pull request because I've been thinking about this (in the background, it is the holidays) for a week since I ran it through ubsan.  I was thinking of just putting a comment in there saying I don't care that it's undefined behavior because any sane implementation should handle it fine.  Or even a comment saying not to pass NULL for interpolation if the user cares.  The other option is getting rid of it entirely and just using a for loop.  It's not like pglCreateProgram is a high volume call or that memcpy is going to be so much faster and make a huge difference.

The other undefined behavior in PortableGL that is the pixel color channel shifts, at least in C.  That one I feel like is probably worth putting the casts to u32 everywhere I shift channels into their proper place.  I'll get to it eventually.

I'll leave this pull request open till I handle it one way or another.

**Comment by e00E** [comment]
(Feel free to ignore my follow up discussion if it's too nitpicky. It's not a huge issue but I like arguing the point. I just happened to see it when glancing over the code so I made the PR.)

I like the for loop the most because it is the clearest, simplest way to express what you want to do. The compiler probably turns it into a memcpy anyway and even if it doesn't, as you said the performance difference doesn't matter here.
Telling users to not pass null doesn't make sense because even when n is 0 you need to pass some *valid* pointer. So you'd need to create a valid pointer even though it isn't used. In languages with a more powerful type system we would be passing some kind of optional but since this is C we have this ambiguity where either the pointer is null and the count is 0 or the pointer is not null and the count > 0.
I don't like accepting the UB. While I agree that right now this doesn't cause any issues and existing implementations do handle it fine, that can change in the future with different compilers or standard libraries. Intentionally leaving UB in the code feels irresponsible.

**Comment by rswinkle** [comment]
Yeah, the for loop is what I was leaning toward though I really do think the chances of a future standard library memcpy implementation dereferencing the NULL pointer and not just exiting out immediately when n is 0 is so remote as to be essentially nil (now I just have to work naught into the sentence and I'll have basically every way of saying zero).

I know programmers have been complaining about getting bitten by undefined or implementation defined behaviors in C/C++ for a long time, but for whatever reason, I've never run into problems with them.  I assume it's a combination of most compilers doing the same sane thing and my programming style and projects naturally avoiding those edge cases.

Happy New Year.

**Comment by e00E** [comment]
Happy new year to you too.

What I meant by ambiguity is that because there are two parameters describing the data there is some space for confusion. Someone could set the pointer to null and the size to !=0 even though that doesn't make sense. With a different type system this invalid state could be unexpressable.

The problem with UB is not just the standard library implementation. Often theoretical UB is fine in practice but it turns into a problem when compilers optimize more. In this case the compiler could deduce that you are calling memcpy with null. This is UB so the compiler infers that this code path can't possibly be taken (because it would invoke UB which is not allowed) and removes your whole main function. I don't have a link ready but there are several examples of cases like this on the internet like compilers removing naive integer overflow checks because the check itself would be UB and so cannot possibly happen.

Another argument in favor of removing benign UB (even though I believe it is never benign) that it hides malign UB. If Ubsan shows a thousand instances of UB then it is hard to start fixing them and not introducing new ones in the same way it is hard to work on projects that have a thousand compilation warnings already.

**Comment by rswinkle** [comment]
> What I meant by ambiguity is that because there are two parameters describing the data there is some space for confusion. Someone could set the pointer to null and the size to !=0 even though that doesn't make sense. With a different type system this invalid state could be unexpressable.

True, but I consider that a programmer error and anything bad that happens is self inflicted and it doesn't even fall under undefined behavior.

> The problem with UB is not just the standard library implementation. Often theoretical UB is fine in practice but it turns into a problem when compilers optimize more. In this case the compiler could deduce that you are calling memcpy with null. This is UB so the compiler infers that this code path can't possibly be taken (because it would invoke UB which is not allowed) and removes your whole main function. I don't have a link ready but there are several examples of cases like this on the internet like compilers removing naive integer overflow checks because the check itself would be UB and so cannot possibly happen.

That doesn't quite make sense to me but I know what you're talking about and I think any optimization that makes an assumption rather than dealing what the programmer actually explicitly said is a bad optimization and shouldn't exist or at least should be explicitly opt-in.  This is the argument against strict aliasing optimizations for example.

> Another argument in favor of removing benign UB (even though I believe it is never benign) that it hides malign UB. If Ubsan shows a thousand instances of UB then it is hard to start fixing them and not introducing new ones in the same way it is hard to work on projects that have a thousand compilation warnings already.

Well at least in examples and testing there were only those 2.  I still need to run demos through ubsan but I don't really expect any more, especially in PGL itself.

**Pull request closed without merging**
